// Field definitions used by the add/edit forms and tables.
//
// When a resource already has records, the form uses the fields found on the
// real records and these lists only supply types/labels. When there are no
// records yet, these lists decide what the "Add" form shows.
//
// Types: string | text | number | bool | date | guid | password | ref:<resource> (dropdown of that resource)
//
// All four match the real API (Apihosts includes the host-default fields). Ids are generated by SQL Server and are never
// sent when creating a record.

window.COCKY_SCHEMA = {
  apiaudit: {
    label: "Endpoint",
    labelPlural: "Endpoints",
    verified: true,
    columns: ["id", "description", "apiHostId", "family", "hasAuthEnabled", "isActive", "lastAuditDate"],
    fields: {
      id: "number", auditorId: "number", description: "string", family: "string",
      url: "string", apiRoot: "string", type: "string",
      servicesAttached: "bool", servicesJson: "text",
      iPv4Address: "string", iPv6Address: "string", hostName: "string",
      hasProxy: "bool", proxyEntranceV4: "string", proxyEntranceV6: "string", proxyType: "string",
      databaseFramework: "string", databaseConnectionString: "string", databaseType: "string",
      hasAuthEnabled: "bool", authType: "string",
      auditorName: "string", auditorEmail: "string", auditorEmployeeId: "string", auditorDepartment: "string",
      businessUnitName: "string", businessUnitOwnerId: "number",
      primaryPort: "number", secondaryPort: "number", secondaryV4: "string", secondaryV6: "string",
      fqdn: "string", osType: "string", frameworkVersion: "string",
      groupId: "number", groupDescription: "string", buildingId: "number", buildingName: "string",
      techContactName: "string", techContactEmail: "string", techContactFax: "string", techContactPhone: "string",
      securityEmail: "string", securityPhone: "string", dbaId: "number", dbaName: "string",
      hashType: "string", endpointType: "string", sslSupported: "bool", httpSupported: "bool",
      httpPortV4: "number", httpPortV6: "number", corsPath: "string",
      allowedRanges: "string", deniedRanges: "string",
      createdDate: "date", modifiedDate: "date", lastAuditDate: "date", isActive: "bool",
      environment: "string", applicationName: "string", sourceRepository: "string",
      azureSubscriptionId: "guid", azureResourceGroup: "string",
      apiHostId: "ref:apihosts", auditResultId: "number", endpointSecure: "bool",
      swaggerOperationId: "string", swaggerVersion: "string", notes: "text", securityClassification: "string"
    }
  },

  apihosts: {
    label: "Host",
    labelPlural: "Hosts",
    verified: true,
    columns: ["id", "apiHostName", "apiHostUrl", "environment", "groupDescription", "techContactName", "isActive", "lastAuditDate"],
    fields: {
      id: "number", apiHostName: "string", apiHostUrl: "string",
      swaggerUsername: "string", swaggerPassword: "password",
      isSecure: "bool", lastAuditDate: "date", lastAuditId: "number",
      active: "bool", isActive: "bool", createdDate: "date",
      // Host defaults, copied onto every endpoint registered from this host's Swagger
      auditorId: "number", family: "string", iPv4Address: "string", iPv6Address: "string", hostName: "string",
      hasProxy: "bool", proxyEntranceV4: "string", proxyEntranceV6: "string", proxyType: "string",
      databaseFramework: "string", databaseConnectionString: "string", databaseType: "string",
      auditorName: "string", auditorEmail: "string", auditorEmployeeId: "string", auditorDepartment: "string",
      businessUnitName: "string", businessUnitOwnerId: "number",
      primaryPort: "number", secondaryPort: "number", secondaryV4: "string", secondaryV6: "string",
      fqdn: "string", osType: "string", frameworkVersion: "string",
      groupId: "number", groupDescription: "string", buildingId: "number", buildingName: "string",
      techContactName: "string", techContactEmail: "string", techContactFax: "string", techContactPhone: "string",
      securityEmail: "string", securityPhone: "string", dbaId: "number", dbaName: "string", hashType: "string",
      sslSupported: "bool", httpSupported: "bool", httpPortV4: "number", httpPortV6: "number",
      corsPath: "string", allowedRanges: "string", deniedRanges: "string",
      environment: "string", applicationName: "string", sourceRepository: "string",
      azureSubscriptionId: "guid", azureResourceGroup: "string", securityClassification: "string"
    }
  },

  // ApiInterfacesAudit: the services/interfaces registered behind an API's back-end, as reported by the
  // Service Controller's SystemConsole enumeration. One row per interface method. apiAuditId ties a row to
  // the endpoint (ApiAudit) it was discovered for. Discovery only: methods are recorded, never called.
  apiinterfaces: {
    label: "Interface",
    labelPlural: "Interfaces",
    verified: true,
    columns: ["id", "apiAuditId", "interfaceName", "methodName", "serviceLifetime", "implementationName", "isRegistered", "discoveredDate"],
    titles: { apiAuditId: "Endpoint", httpMethod: "HTTP", isRegistered: "Registered", methodName: "Method" },
    fields: {
      id: "number", apiAuditId: "ref:apiaudit",
      controllerName: "string", route: "string", httpMethod: "string",
      interfaceName: "string", implementationName: "string", serviceLifetime: "string",
      methodName: "string", isRegistered: "bool", discoveredDate: "date"
    },
    groups: [
      { title: "Interface", keys: ["apiAuditId", "interfaceName", "methodName", "implementationName", "serviceLifetime", "isRegistered"] },
      { title: "Endpoint mapping", keys: ["controllerName", "route", "httpMethod"] },
      { title: "Status", keys: ["id", "discoveredDate"] }
    ],
    format: {
      // Flag the mutating methods (Create*/Update*/Delete*) — a write/delete on a back-end log service is the finding
      methodName: v => {
        if (v == null || v === "") return '<span class="text-muted">—</span>';
        const s = String(v);
        const badge = /^delete/i.test(s) ? '<span class="badge text-bg-danger ms-1">delete</span>'
          : /^(create|add|insert)/i.test(s) ? '<span class="badge text-bg-warning ms-1">create</span>'
          : /^(update|put|patch|edit)/i.test(s) ? '<span class="badge text-bg-warning ms-1">update</span>'
          : "";
        return `<code>${window.Cocky.esc(s)}</code>${badge}`;
      }
    }
  },

  apiauditresults: {
    label: "Audit",
    labelPlural: "Audits",
    verified: true,
    columns: ["id", "auditDate", "auditorName", "totalApiHosts", "apiHostsInsecure", "totalApiEndpoints", "totalEndpointsInsecure", "notes"],
    fields: {
      id: "number", auditDate: "date",
      totalApiHosts: "number", apiHostsSecure: "number", apiHostsInsecure: "number",
      totalApiEndpoints: "number", totalEndpointsSecure: "number", totalEndpointsInsecure: "number",
      auditorId: "number", auditorName: "string", notes: "text"
    }
  },

  hostexceptions: {
    label: "Host exception",
    labelPlural: "Host exceptions",
    verified: true,
    columns: ["id", "apiHostId", "exceptionType", "reason", "approvedBy", "expirationDate", "active"],
    fields: {
      id: "number", apiHostId: "ref:apihosts", exceptionType: "string", reason: "text",
      approvedBy: "string", approvalDate: "date", expirationDate: "date", active: "bool",
      notes: "text", createdDate: "date"
    },
    format: { expirationDate: (v, r) => window.COCKY_SCHEMA.auditexceptions.format.expirationDate(v, r) }
  },

  // Application (Enterprise.Models.Application): an app that uses one or more host APIs.
  // Which hosts it uses lives in the ApplicationApi link table below, not on the application itself.
  apps: {
    label: "Application",
    labelPlural: "Applications",
    verified: true,
    columns: ["id", "applicationName", "applicationCode", "hostApis", "infra", "endpointTotal", "environment", "ownerName", "isActive"],
    titles: { applicationName: "Application", applicationCode: "Code", hostApis: "Host APIs", infra: "Runs on", endpointTotal: "Endpoints", ownerName: "Owner", isActive: "Active" },
    fields: {
      id: "number", applicationName: "string", applicationCode: "string", description: "text",
      ownerName: "string", ownerEmail: "string", supportGroup: "string", businessUnit: "string",
      environment: "string", inventoryId: "string", isActive: "bool", createdDate: "date", modifiedDate: "date",
      // Build 4.9: where the application runs (a single web server or a web farm).
      // databaseId isn't on Enterprise.Models.Application yet; it's only shown once the API returns it.
      webServerId: "ref:webservers", webFarmId: "ref:webfarms", databaseId: "ref:databases"
    },
    groups: [
      { title: "Application", keys: ["applicationName", "applicationCode", "description", "inventoryId", "environment", "isActive"] },
      { title: "Infrastructure", keys: ["webServerId", "webFarmId", "databaseId"] },
      { title: "Ownership", keys: ["ownerName", "ownerEmail", "supportGroup", "businessUnit"] },
      { title: "Status", keys: ["id", "createdDate", "modifiedDate"] }
    ]
  },

  // ApplicationApi (Enterprise.Models.ApplicationApi): one row per host API an application uses
  apphosts: {
    label: "Application API link",
    labelPlural: "Application API links",
    verified: true,
    columns: ["id", "applicationId", "apiHostId", "createdDate"],
    fields: { id: "number", applicationId: "ref:apps", apiHostId: "ref:apihosts", createdDate: "date" }
  },

  auditexceptions: {
    label: "Exception",
    labelPlural: "Exceptions",
    verified: true,
    columns: ["id", "apiAuditId", "apiRootUrl", "apiEndpointPath", "reason", "approvedBy", "expirationDate", "active"],
    fields: {
      id: "number", apiAuditId: "ref:apiaudit",
      apiRootUrl: "string", apiEndpointPath: "string",   // scope: whole API root and/or path pattern (* = wildcard)
      reason: "text", approvedBy: "string",
      approvalDate: "date", expirationDate: "date", active: "bool",
      notes: "text", createdDate: "date"
    },
    format: {
      // Show an "Expired" badge when the expiration date has passed
      expirationDate: v => {
        if (!v) return '<span class="badge text-bg-info">No expiry</span>';
        const d = Cocky.parseDate(v);
        return Cocky.fmtValue(v, "date") + (d && d < new Date() ? ' <span class="badge text-bg-danger">Expired</span>' : "");
      }
    }
  }
};

// ---- Infrastructure (build 4.9) ----
// JSON names are the ASP.NET camelCase of the SQL columns (TLSVersion -> tlsVersion, AzureURL -> azureURL,
// CName1 -> cName1). When the tables have records, the forms use the names the API actually returns.
// Computed columns: "findings" (Infra Audit result), plus the per-page ones noted below.
const INFRA_COMMON = {
  azure: ["azureURL", "azureIP", "azureSubscription", "resourceGroup", "region"],
  dns: ["cName1", "cName2", "cName3"],
  ownership: ["owner", "supportTeam", "environment", "location"]
};
Object.assign(window.COCKY_SCHEMA, {
  webservers: {
    label: "Web server", labelPlural: "Web servers", verified: true,
    columns: ["id", "serverName", "hostname", "environment", "webServerType", "operatingSystem", "tlsVersion", "publicFacing", "farms", "findings", "active"],
    titles: { tlsVersion: "TLS", publicFacing: "Public", webServerType: "Type", operatingSystem: "OS", farms: "Farms", findings: "Findings" },
    fields: {
      id: "number", inventoryId: "string", serverName: "string", hostname: "string", ipAddress: "string",
      operatingSystem: "string", webServerType: "string", version: "string",
      azureURL: "string", azureIP: "string", cName1: "string", cName2: "string", cName3: "string",
      applicationURL: "string", environment: "string", location: "string",
      azureSubscription: "string", resourceGroup: "string", region: "string",
      owner: "string", supportTeam: "string", tlsVersion: "string",
      publicFacing: "bool", active: "bool", notes: "text", createdDate: "date"
    },
    groups: [
      { title: "Server", keys: ["serverName", "hostname", "ipAddress", "inventoryId", "operatingSystem", "webServerType", "version", "tlsVersion", "applicationURL", "publicFacing", "active"] },
      { title: "Ownership", keys: INFRA_COMMON.ownership },
      { title: "DNS names", keys: INFRA_COMMON.dns },
      { title: "Azure", keys: INFRA_COMMON.azure },
      { title: "Notes & status", keys: ["notes", "id", "createdDate"] }
    ]
  },

  webfarms: {
    label: "Web farm", labelPlural: "Web farms", verified: true,
    columns: ["id", "farmName", "environment", "loadBalancerName", "url", "tlsVersion", "publicFacing", "members", "findings", "enabled"],
    titles: { farmName: "Farm", loadBalancerName: "Load balancer", url: "URL", tlsVersion: "TLS", publicFacing: "Public", members: "Member servers", findings: "Findings" },
    fields: {
      id: "number", inventoryId: "string", farmName: "string", description: "text",
      loadBalancerName: "string", loadBalancerType: "string", virtualIpAddress: "string", url: "string",
      azureURL: "string", azureIP: "string", cName1: "string", cName2: "string", cName3: "string",
      applicationURL: "string", environment: "string", location: "string",
      azureSubscription: "string", resourceGroup: "string", region: "string",
      owner: "string", supportTeam: "string", tlsVersion: "string", backendPoolCount: "number",
      healthProbeUrl: "string", publicFacing: "bool", enabled: "bool", notes: "text", createdDate: "date"
    },
    groups: [
      { title: "Farm", keys: ["farmName", "description", "inventoryId", "url", "applicationURL", "tlsVersion", "publicFacing", "enabled"] },
      { title: "Load balancer", keys: ["loadBalancerName", "loadBalancerType", "virtualIpAddress", "backendPoolCount", "healthProbeUrl"] },
      { title: "Ownership", keys: INFRA_COMMON.ownership },
      { title: "DNS names", keys: INFRA_COMMON.dns },
      { title: "Azure", keys: INFRA_COMMON.azure },
      { title: "Notes & status", keys: ["notes", "id", "createdDate"] }
    ]
  },

  // Link table: which web servers are in which farm (no PUT: add or remove only)
  webfarmservers: {
    label: "Farm member", labelPlural: "Farm members", verified: true,
    columns: ["id", "webFarmId", "webServerId"],
    fields: { id: "number", webFarmId: "ref:webfarms", webServerId: "ref:webservers" }
  },

  databaseservers: {
    label: "Database server", labelPlural: "Database servers", verified: true,
    columns: ["id", "serverName", "hostname", "environment", "databasePlatform", "version", "backupSolution", "publicFacing", "databaseCount", "findings", "active"],
    titles: { databasePlatform: "Platform", backupSolution: "Backup", publicFacing: "Public", databaseCount: "Databases", findings: "Findings" },
    fields: {
      id: "number", inventoryId: "string", serverName: "string", hostname: "string", ipAddress: "string",
      databasePlatform: "string", version: "string", databaseInstance: "string",
      azureURL: "string", azureIP: "string", cName1: "string", cName2: "string", cName3: "string",
      environment: "string", location: "string",
      azureSubscription: "string", resourceGroup: "string", region: "string",
      owner: "string", supportTeam: "string", backupSolution: "string", recoveryModel: "string",
      publicFacing: "bool", active: "bool", notes: "text", createdDate: "date"
    },
    groups: [
      { title: "Server", keys: ["serverName", "hostname", "ipAddress", "inventoryId", "databasePlatform", "version", "databaseInstance", "publicFacing", "active"] },
      { title: "Backup", keys: ["backupSolution", "recoveryModel"] },
      { title: "Ownership", keys: INFRA_COMMON.ownership },
      { title: "DNS names", keys: INFRA_COMMON.dns },
      { title: "Azure", keys: INFRA_COMMON.azure },
      { title: "Notes & status", keys: ["notes", "id", "createdDate"] }
    ]
  },

  databases: {
    label: "Database", labelPlural: "Databases", verified: true,
    columns: ["id", "databaseName", "databaseServerId", "databaseType", "classification", "dataFlags", "encryptionEnabled", "backupRequired", "usedBy", "findings", "active"],
    titles: { databaseName: "Database", databaseServerId: "Server", databaseType: "Type", dataFlags: "Holds", encryptionEnabled: "Encrypted", backupRequired: "Backup req.", usedBy: "Used by", findings: "Findings" },
    fields: {
      id: "number", inventoryId: "string", databaseServerId: "ref:databaseservers", databaseName: "string",
      description: "text", databaseType: "string", version: "string", classification: "string",
      owner: "string", supportTeam: "string",
      backupRequired: "bool", encryptionEnabled: "bool", containsPII: "bool", containsPHI: "bool", containsPCI: "bool",
      active: "bool", notes: "text", createdDate: "date"
    },
    // New records start with the table's defaults (BackupRequired = 1)
    defaults: { backupRequired: true },
    groups: [
      { title: "Database", keys: ["databaseName", "databaseServerId", "description", "inventoryId", "databaseType", "version", "active"] },
      { title: "Data protection", keys: ["classification", "containsPII", "containsPHI", "containsPCI", "encryptionEnabled", "backupRequired"] },
      { title: "Ownership", keys: ["owner", "supportTeam"] },
      { title: "Notes & status", keys: ["notes", "id", "createdDate"] }
    ]
  }
});

// ---- Form sections ----
// The add/edit dialog groups fields under these headings. A section starts expanded when it's
// first, or when the record already has something filled in there.
const DETAIL_GROUPS = [
  { detail: true, title: "Ownership (department / building)", keys: ["businessUnitName", "businessUnitOwnerId", "groupId", "groupDescription", "buildingId", "buildingName"] },
  { detail: true, title: "Ops contacts", keys: ["techContactName", "techContactEmail", "techContactPhone", "techContactFax", "securityEmail", "securityPhone"] },
  { detail: true, title: "Auditor", keys: ["auditorId", "auditorName", "auditorEmail", "auditorEmployeeId", "auditorDepartment"] },
  { detail: true, title: "Platform & data", keys: ["environment", "applicationName", "osType", "frameworkVersion", "databaseFramework", "databaseType", "databaseConnectionString", "dbaId", "dbaName", "hashType", "sourceRepository", "securityClassification"] },
  { detail: true, title: "Azure", keys: ["azureSubscriptionId", "azureResourceGroup"] },
  { detail: true, title: "Network", keys: ["hostName", "fqdn", "iPv4Address", "iPv6Address", "primaryPort", "secondaryPort", "secondaryV4", "secondaryV6", "httpPortV4", "httpPortV6", "sslSupported", "httpSupported", "hasProxy", "proxyType", "proxyEntranceV4", "proxyEntranceV6", "corsPath", "allowedRanges", "deniedRanges"] },
  { detail: true, title: "Services", keys: ["servicesAttached", "servicesJson"] }
];
window.COCKY_SCHEMA.apihosts.defaultView = "core";   // Edit shows core fields; the Details button shows the rest
window.COCKY_SCHEMA.apihosts.groups = [
  { title: "API & Swagger", keys: ["apiHostName", "apiHostUrl", "swaggerUsername", "swaggerPassword", "family", "isSecure", "active", "isActive"] },
  ...DETAIL_GROUPS,
  { title: "Audit status", keys: ["id", "lastAuditDate", "lastAuditId", "createdDate"] }
];
window.COCKY_SCHEMA.apiaudit.groups = [
  { title: "Endpoint", keys: ["description", "type", "endpointType", "url", "apiRoot", "apiHostId", "family", "hasAuthEnabled", "authType", "endpointSecure", "isActive", "swaggerOperationId", "swaggerVersion", "notes"] },
  ...DETAIL_GROUPS,
  { title: "Audit status", keys: ["id", "lastAuditDate", "auditResultId", "createdDate", "modifiedDate"] }
];

// ---- Run Audit -> /api/ApiAuditResults ----
// One audit result = one summary record for the whole run.
// pairs = [{ endpoint, check }], hosts = all Apihost records.

// Counts for the run. An endpoint is "secure" if it was tested over HTTPS.
// A host is "secure" if its apiHostUrl is HTTPS (falls back to its isSecure flag).
window.summarizeAudit = function (pairs, hosts) {
  const hostIds = [...new Set(pairs.map(p => p.endpoint.apiHostId).filter(id => id != null))];
  const auditedHosts = hostIds.map(id => hosts.find(h => h.id === id)).filter(Boolean);
  const hostSecure = h => /^https:/i.test(h.apiHostUrl || "") || (!h.apiHostUrl && !!h.isSecure);
  const epSecure = pairs.filter(p => p.check.secure).length;
  const hSecure = auditedHosts.filter(hostSecure).length;
  return {
    totalApiHosts: auditedHosts.length,
    apiHostsSecure: hSecure,
    apiHostsInsecure: auditedHosts.length - hSecure,
    totalApiEndpoints: pairs.length,
    totalEndpointsSecure: epSecure,
    totalEndpointsInsecure: pairs.length - epSecure
  };
};

window.buildAuditResultPayload = function (pairs, hosts, { auditorId, auditorName, notes }) {
  const lines = pairs.map(({ endpoint: e, check: c }) => {
    const head = `#${e.id} ${e.description || ""} - ${c.verdict.toUpperCase()}` +
      `${c.status ? ` (HTTP ${c.status}` : " ("}${c.ms != null ? `${c.status ? ", " : ""}${Math.round(c.ms)} ms` : ""}) ${c.url || "(no url)"}`;
    const issues = c.findings.filter(f => f.level === "warn" || f.level === "fail")
      .map(f => `   [${f.level.toUpperCase()}] ${f.text}`);
    return [head.replace(" ()", ""), ...issues].join("\n");
  });
  let text = [notes, lines.join("\n")].filter(Boolean).join("\n\n");
  if (text.length > 4000) text = text.slice(0, 3990) + "\n…";
  return {
    auditDate: new Date().toISOString(),
    ...window.summarizeAudit(pairs, hosts),
    auditorId: auditorId || 0,
    auditorName: auditorName || null,
    notes: text
  };
};
