// <auto-generated />
using System;
using Enterprise.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace statsback798.Migrations
{
    [DbContext(typeof(EnterpriseContext))]
    [Migration("20260905042957_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Enterprise.Models.Adminlog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acknowledged")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Managerescid")
                        .HasColumnType("int");

                    b.Property<int?>("Techid")
                        .HasColumnType("int");

                    b.Property<string>("Threatlevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Userid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Adminlogs");
                });

            modelBuilder.Entity("Enterprise.Models.Allstock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Avgdividend")
                        .HasColumnType("float")
                        .HasColumnName("avgdividend");

                    b.Property<double?>("Change")
                        .HasColumnType("float")
                        .HasColumnName("change");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Company");

                    b.Property<double?>("Div2016")
                        .HasColumnType("float")
                        .HasColumnName("Div_2016");

                    b.Property<double?>("Div2017")
                        .HasColumnType("float")
                        .HasColumnName("Div_2017");

                    b.Property<double?>("Div2018")
                        .HasColumnType("float")
                        .HasColumnName("Div_2018");

                    b.Property<double?>("Div2019")
                        .HasColumnType("float")
                        .HasColumnName("Div_2019");

                    b.Property<double?>("Div2020")
                        .HasColumnType("float")
                        .HasColumnName("Div_2020");

                    b.Property<double?>("Div2021")
                        .HasColumnType("float")
                        .HasColumnName("Div_2021");

                    b.Property<double?>("Div2022")
                        .HasColumnType("float")
                        .HasColumnName("Div_2022");

                    b.Property<double?>("Div2023")
                        .HasColumnType("float")
                        .HasColumnName("Div_2023");

                    b.Property<double?>("Div2024")
                        .HasColumnType("float")
                        .HasColumnName("Div_2024");

                    b.Property<double?>("Div2025")
                        .HasColumnType("float")
                        .HasColumnName("Div_2025");

                    b.Property<double?>("Div2026")
                        .HasColumnType("float")
                        .HasColumnName("Div_2026");

                    b.Property<double?>("Fiveyeardivproj")
                        .HasColumnType("float")
                        .HasColumnName("fiveyeardivproj");

                    b.Property<double?>("Fiveyearequityproj")
                        .HasColumnType("float")
                        .HasColumnName("fiveyearequityproj");

                    b.Property<double?>("Price2016")
                        .HasColumnType("float")
                        .HasColumnName("Price_2016");

                    b.Property<double?>("Price2017")
                        .HasColumnType("float")
                        .HasColumnName("Price_2017");

                    b.Property<double?>("Price2018")
                        .HasColumnType("float")
                        .HasColumnName("Price_2018");

                    b.Property<double?>("Price2019")
                        .HasColumnType("float")
                        .HasColumnName("Price_2019");

                    b.Property<double?>("Price2020")
                        .HasColumnType("float")
                        .HasColumnName("Price_2020");

                    b.Property<double?>("Price2021")
                        .HasColumnType("float")
                        .HasColumnName("Price_2021");

                    b.Property<double?>("Price2022")
                        .HasColumnType("float")
                        .HasColumnName("Price_2022");

                    b.Property<double?>("Price2023")
                        .HasColumnType("float")
                        .HasColumnName("Price_2023");

                    b.Property<double?>("Price2024")
                        .HasColumnType("float")
                        .HasColumnName("Price_2024");

                    b.Property<double?>("Price2025")
                        .HasColumnType("float")
                        .HasColumnName("Price_2025");

                    b.Property<double?>("Price2026")
                        .HasColumnType("float")
                        .HasColumnName("Price_2026");

                    b.Property<double?>("PriceEnd")
                        .HasColumnType("float")
                        .HasColumnName("price_end");

                    b.Property<double?>("PriceStart")
                        .HasColumnType("float")
                        .HasColumnName("price_start");

                    b.Property<string>("Sector")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sector");

                    b.Property<string>("Selected")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Shares500")
                        .HasColumnType("float")
                        .HasColumnName("shares500");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Source");

                    b.Property<string>("Ticker")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ticker");

                    b.Property<double?>("Totaldividends")
                        .HasColumnType("float")
                        .HasColumnName("totaldividends");

                    b.Property<double?>("Totalfiveyearview")
                        .HasColumnType("float")
                        .HasColumnName("totalfiveyearview");

                    b.Property<double?>("Totalreturn")
                        .HasColumnType("float")
                        .HasColumnName("totalreturn");

                    b.Property<double?>("Totalreturnover10")
                        .HasColumnType("float")
                        .HasColumnName("totalreturnover10");

                    b.Property<double?>("Totalspend")
                        .HasColumnType("float")
                        .HasColumnName("totalspend");

                    b.HasKey("Id");

                    b.ToTable("allstocks", (string)null);
                });

            modelBuilder.Entity("Enterprise.Models.Apilog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apiname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apinumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apiresult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eptype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Hashid")
                        .HasColumnType("int");

                    b.Property<string>("Parameterlist")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Apilogs");
                });

            modelBuilder.Entity("Enterprise.Models.CipherSupport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CipherKey")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CipherKey");

                    b.Property<string>("CipherName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CipherName");

                    b.Property<string>("DateCreated")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DateCreated");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<int?>("IsActive")
                        .HasColumnType("int")
                        .HasColumnName("IsActive");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.ToTable("CipherSupport", (string)null);
                });

            modelBuilder.Entity("Enterprise.Models.CockyCipherBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CockyCipherBlocks");
                });

            modelBuilder.Entity("Enterprise.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Enterprise.Models.Keyassignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeliveredToUser")
                        .HasColumnType("int");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrivateKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Keyassignments");
                });

            modelBuilder.Entity("Enterprise.Models.Learndetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cataloguesku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Certauthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Employee")
                        .HasColumnType("int");

                    b.Property<string>("Employeeid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Employeeidasint")
                        .HasColumnType("int");

                    b.Property<string>("Enddate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Learningmodulesid")
                        .HasColumnType("int");

                    b.Property<string>("Startdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Userid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Learndetails");
                });

            modelBuilder.Entity("Enterprise.Models.Learnlog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cataloguesku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Certauthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emplid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Employee")
                        .HasColumnType("int");

                    b.Property<string>("Employeeid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Employeeidasint")
                        .HasColumnType("int");

                    b.Property<string>("Enddate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Learningmodulesid")
                        .HasColumnType("int");

                    b.Property<string>("Startdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Userid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Learnlogs");
                });

            modelBuilder.Entity("Enterprise.Models.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("PortfolioTargetInvestment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Portfolios", (string)null);
                });

            modelBuilder.Entity("Enterprise.Models.PortfolioStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<string>("PreviousDayDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PreviousDayPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Shares")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("StockTargetInvestment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PortfolioStocks", (string)null);
                });

            modelBuilder.Entity("Enterprise.Models.Sectorsummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Avgdividend")
                        .HasColumnType("float")
                        .HasColumnName("avgdividend");

                    b.Property<double?>("Change")
                        .HasColumnType("float")
                        .HasColumnName("change");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Company");

                    b.Property<double?>("Fiveyeardivproj")
                        .HasColumnType("float")
                        .HasColumnName("fiveyeardivproj");

                    b.Property<double?>("Fiveyearequityproj")
                        .HasColumnType("float")
                        .HasColumnName("fiveyearequityproj");

                    b.Property<double?>("PriceEnd")
                        .HasColumnType("float")
                        .HasColumnName("price_end");

                    b.Property<double?>("PriceStart")
                        .HasColumnType("float")
                        .HasColumnName("price_start");

                    b.Property<string>("Sector")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sector");

                    b.Property<string>("Selected")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("selected");

                    b.Property<double?>("Shares500")
                        .HasColumnType("float")
                        .HasColumnName("shares500");

                    b.Property<string>("Ticker")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ticker");

                    b.Property<double?>("Totaldividends")
                        .HasColumnType("float")
                        .HasColumnName("totaldividends");

                    b.Property<double?>("Totalfiveyearview")
                        .HasColumnType("float")
                        .HasColumnName("totalfiveyearview");

                    b.Property<double?>("Totalreturn")
                        .HasColumnType("float")
                        .HasColumnName("totalreturn");

                    b.Property<double?>("Totalreturnover10")
                        .HasColumnType("float")
                        .HasColumnName("totalreturnover10");

                    b.Property<double?>("Totalspend")
                        .HasColumnType("float")
                        .HasColumnName("totalspend");

                    b.Property<int?>("userid")
                        .HasColumnType("int")
                        .HasColumnName("userid");

                    b.Property<string>("useridasstring")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("useridasstring");

                    b.HasKey("Id");

                    b.ToTable("sectorssummaries", (string)null);
                });

            modelBuilder.Entity("Enterprise.Models.Sessionlog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Hashid")
                        .HasColumnType("int");

                    b.Property<string>("Moduleid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Sessionend")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Sessionstart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sessionlogs");
                });

            modelBuilder.Entity("Enterprise.Models.Superuserlog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acknowledged")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Managerescid")
                        .HasColumnType("int");

                    b.Property<int?>("Techid")
                        .HasColumnType("int");

                    b.Property<string>("Threatlevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Userid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Superuserlogs");
                });

            modelBuilder.Entity("Enterprise.Models.SystemStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Avgdividend")
                        .HasColumnType("float");

                    b.Property<double?>("Change")
                        .HasColumnType("float");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("US");

                    b.Property<double?>("Div2016")
                        .HasColumnType("float");

                    b.Property<double?>("Div2017")
                        .HasColumnType("float");

                    b.Property<double?>("Div2018")
                        .HasColumnType("float");

                    b.Property<double?>("Div2019")
                        .HasColumnType("float");

                    b.Property<double?>("Div2020")
                        .HasColumnType("float");

                    b.Property<double?>("Div2021")
                        .HasColumnType("float");

                    b.Property<double?>("Div2022")
                        .HasColumnType("float");

                    b.Property<double?>("Div2023")
                        .HasColumnType("float");

                    b.Property<double?>("Div2024")
                        .HasColumnType("float");

                    b.Property<double?>("Div2025")
                        .HasColumnType("float");

                    b.Property<double?>("Div2026")
                        .HasColumnType("float");

                    b.Property<double?>("Fiveyeardivproj")
                        .HasColumnType("float");

                    b.Property<double?>("Fiveyearequityproj")
                        .HasColumnType("float");

                    b.Property<double?>("Price2016")
                        .HasColumnType("float");

                    b.Property<double?>("Price2017")
                        .HasColumnType("float");

                    b.Property<double?>("Price2018")
                        .HasColumnType("float");

                    b.Property<double?>("Price2019")
                        .HasColumnType("float");

                    b.Property<double?>("Price2020")
                        .HasColumnType("float");

                    b.Property<double?>("Price2021")
                        .HasColumnType("float");

                    b.Property<double?>("Price2022")
                        .HasColumnType("float");

                    b.Property<double?>("Price2023")
                        .HasColumnType("float");

                    b.Property<double?>("Price2024")
                        .HasColumnType("float");

                    b.Property<double?>("Price2025")
                        .HasColumnType("float");

                    b.Property<double?>("Price2026")
                        .HasColumnType("float");

                    b.Property<double?>("PriceEnd")
                        .HasColumnType("float");

                    b.Property<double?>("PriceStart")
                        .HasColumnType("float");

                    b.Property<string>("PrimaryExchange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryExchange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Selected")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Shares500")
                        .HasColumnType("float");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Totaldividends")
                        .HasColumnType("float");

                    b.Property<double?>("Totalfiveyearview")
                        .HasColumnType("float");

                    b.Property<double?>("Totalreturn")
                        .HasColumnType("float");

                    b.Property<double?>("Totalreturnover10")
                        .HasColumnType("float");

                    b.Property<double?>("Totalspend")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("SystemStocks", (string)null);
                });

            modelBuilder.Entity("Enterprise.Models.TradeOrders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExecutionPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<int>("PortfolioStockId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TraderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("PortfolioStockId");

                    b.HasIndex("TraderId");

                    b.ToTable("TradeOrders");
                });

            modelBuilder.Entity("Enterprise.Models.Trader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StaffUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Traders");
                });

            modelBuilder.Entity("Enterprise.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accountactiondate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Accountactiondescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Accountstatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Azureid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Btn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Companyid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Displayname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Employee")
                        .HasColumnType("int");

                    b.Property<string>("Employeeid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Groupid1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Groupid2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Groupid3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Groupid4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Groupid5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hashedpassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Iscertified")
                        .HasColumnType("int");

                    b.Property<int?>("Jid")
                        .HasColumnType("int");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Microsoftid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ncrid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oracleid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Passwordtype")
                        .HasColumnType("int");

                    b.Property<string>("Plainpassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profileurl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resettoken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Resettokenexpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Userid")
                        .HasColumnType("int");

                    b.Property<string>("Useridstring")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Enterprise.Models.UserLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsPrimary")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserLocations");
                });

            modelBuilder.Entity("Enterprise.Models.Useraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Acknowledged")
                        .HasColumnType("int");

                    b.Property<string>("Actiondate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Actionpriority")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Userid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Useractions");
                });

            modelBuilder.Entity("Enterprise.Models.Usergroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Groupcompanyid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Groupdescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Groupid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Groupownerid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usergroups");
                });

            modelBuilder.Entity("Enterprise.Models.Userhelp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bestcontactnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Emplid")
                        .HasColumnType("int");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Replied")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Repliedmanageremail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Repliedmanagerid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Repliedmanagerphone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsedate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Ticketdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ticketid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Userid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Userhelps");
                });

            modelBuilder.Entity("Enterprise.Models.Userlog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hashedpassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Hashid")
                        .HasColumnType("int");

                    b.Property<string>("Loginstatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uiorigin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("uid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Userlog");
                });

            modelBuilder.Entity("Enterprise.Models.Usernotice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emailaddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emailgwtype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NoticeDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Noticetype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Userid")
                        .HasColumnType("int");

                    b.Property<string>("Useridstring")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usernotice");
                });

            modelBuilder.Entity("Enterprise.Models.Userprofile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Activepictureurl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Branchid")
                        .HasColumnType("int");

                    b.Property<int?>("Buid")
                        .HasColumnType("int");

                    b.Property<string>("Cellphone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("CipherSupportId")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Companyid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Defaultinstanceid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Defaultshardid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employeeid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facebookurl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Googleurl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instagramurl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Linkedinurl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Managerid")
                        .HasColumnType("int");

                    b.Property<string>("Maritalstatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postalzip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pronoun")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Regionid")
                        .HasColumnType("int");

                    b.Property<int?>("Sms")
                        .HasColumnType("int");

                    b.Property<string>("Stateregion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Targetcipher")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("University")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("University1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("University2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Userid")
                        .HasColumnType("int");

                    b.Property<string>("Vimeourl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Userprofiles");
                });

            modelBuilder.Entity("Enterprise.Models.Usersession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Acknowledged")
                        .HasColumnType("int");

                    b.Property<int?>("Actionpriority")
                        .HasColumnType("int");

                    b.Property<string>("FacebookToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MicrosoftToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sessioncomplete")
                        .HasColumnType("int");

                    b.Property<string>("Sessiondescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sessionemail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sessionend")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sessionfirstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sessionfullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sessionlastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sessionrecorded")
                        .HasColumnType("int");

                    b.Property<string>("Sessionrecordurl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sessionstart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sessionusername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Targetcipher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Twofactorkey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Twofactorkeyemaildestination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Twofactorkeysmsdestination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Twofactorprovider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Twofactorproviderauthstring")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Twofactorprovidertoken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Userid")
                        .HasColumnType("int");

                    b.Property<string>("Useridasstring")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usersessions");
                });

            modelBuilder.Entity("Enterprise.Models.Keyassignment", b =>
                {
                    b.HasOne("Enterprise.Models.Usersession", "Session")
                        .WithMany("Keyassignments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Enterprise.Models.Portfolio", b =>
                {
                    b.HasOne("Enterprise.Models.Customer", null)
                        .WithMany("Portfolios")
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("Enterprise.Models.TradeOrders", b =>
                {
                    b.HasOne("Enterprise.Models.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enterprise.Models.PortfolioStock", "PortfolioStock")
                        .WithMany()
                        .HasForeignKey("PortfolioStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enterprise.Models.Trader", "Trader")
                        .WithMany("TradeOrders")
                        .HasForeignKey("TraderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");

                    b.Navigation("PortfolioStock");

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("Enterprise.Models.Customer", b =>
                {
                    b.Navigation("Portfolios");
                });

            modelBuilder.Entity("Enterprise.Models.Trader", b =>
                {
                    b.Navigation("TradeOrders");
                });

            modelBuilder.Entity("Enterprise.Models.Usersession", b =>
                {
                    b.Navigation("Keyassignments");
                });
#pragma warning restore 612, 618
        }
    }
}
