// Field definitions used by the add/edit forms and tables.
//
// When a resource already has records, the form uses the fields found on the
// real records and these lists only supply types/labels. When there are no
// records yet, these lists decide what the "Add" form shows.
//
// Types: string | text | number | bool | date | guid | password | ref:<resource> (dropdown of that resource)
//
// All four match the real API (Apihosts includes the host-default fields). Ids are generated by SQL Server and are never
// sent when creating a record.

window.COCKY_SCHEMA = {
  apiaudit: {
    label: "Endpoint",
    labelPlural: "Endpoints",
    verified: true,
    columns: ["id", "description", "apiHostId", "family", "hasAuthEnabled", "isActive", "lastAuditDate"],
    fields: {
      id: "number", auditorId: "number", description: "string", family: "string",
      url: "string", apiRoot: "string", type: "string",
      servicesAttached: "bool", servicesJson: "text",
      iPv4Address: "string", iPv6Address: "string", hostName: "string",
      hasProxy: "bool", proxyEntranceV4: "string", proxyEntranceV6: "string", proxyType: "string",
      databaseFramework: "string", databaseConnectionString: "string", databaseType: "string",
      hasAuthEnabled: "bool", authType: "string",
      auditorName: "string", auditorEmail: "string", auditorEmployeeId: "string", auditorDepartment: "string",
      businessUnitName: "string", businessUnitOwnerId: "number",
      primaryPort: "number", secondaryPort: "number", secondaryV4: "string", secondaryV6: "string",
      fqdn: "string", osType: "string", frameworkVersion: "string",
      groupId: "number", groupDescription: "string", buildingId: "number", buildingName: "string",
      techContactName: "string", techContactEmail: "string", techContactFax: "string", techContactPhone: "string",
      securityEmail: "string", securityPhone: "string", dbaId: "number", dbaName: "string",
      hashType: "string", endpointType: "string", sslSupported: "bool", httpSupported: "bool",
      httpPortV4: "number", httpPortV6: "number", corsPath: "string",
      allowedRanges: "string", deniedRanges: "string",
      createdDate: "date", modifiedDate: "date", lastAuditDate: "date", isActive: "bool",
      environment: "string", applicationName: "string", sourceRepository: "string",
      azureSubscriptionId: "guid", azureResourceGroup: "string",
      apiHostId: "ref:apihosts", auditResultId: "number", endpointSecure: "bool",
      swaggerOperationId: "string", swaggerVersion: "string", notes: "text", securityClassification: "string",
      // Build 5.6: set by Run Audit when the run is saved (see apiaudit.html timing())
      lastResponseMs: "number", lastStatusCode: "number"
    }
  },

  apihosts: {
    label: "Host",
    labelPlural: "Hosts",
    verified: true,
    columns: ["id", "apiHostName", "apiHostUrl", "hostOs", "hostedBy", "environment", "groupDescription", "techContactName", "isActive", "lastAuditDate"],
    titles: { hostOs: "Operating system", hostedBy: "Hosted by" },
    fields: {
      id: "number", apiHostName: "string", apiHostUrl: "string",
      swaggerUsername: "string", swaggerPassword: "password",
      isSecure: "bool", lastAuditDate: "date", lastAuditId: "number",
      active: "bool", isActive: "bool", createdDate: "date",
      // Host defaults, copied onto every endpoint registered from this host's Swagger
      auditorId: "number", family: "string", iPv4Address: "string", iPv6Address: "string", hostName: "string",
      hasProxy: "bool", proxyEntranceV4: "string", proxyEntranceV6: "string", proxyType: "string",
      databaseFramework: "string", databaseConnectionString: "string", databaseType: "string",
      auditorName: "string", auditorEmail: "string", auditorEmployeeId: "string", auditorDepartment: "string",
      businessUnitName: "string", businessUnitOwnerId: "number",
      primaryPort: "number", secondaryPort: "number", secondaryV4: "string", secondaryV6: "string",
      fqdn: "string", osType: "string", frameworkVersion: "string",
      groupId: "number", groupDescription: "string", buildingId: "number", buildingName: "string",
      techContactName: "string", techContactEmail: "string", techContactFax: "string", techContactPhone: "string",
      securityEmail: "string", securityPhone: "string", dbaId: "number", dbaName: "string", hashType: "string",
      sslSupported: "bool", httpSupported: "bool", httpPortV4: "number", httpPortV6: "number",
      corsPath: "string", allowedRanges: "string", deniedRanges: "string",
      environment: "string", applicationName: "string", sourceRepository: "string",
      azureSubscriptionId: "guid", azureResourceGroup: "string", securityClassification: "string"
    }
  },

  // ApiInterfacesAudit: the services/interfaces registered behind an API's back-end, as reported by that API's
  // SystemConsole. One row per interface method. apiHostId = the host (API) it was discovered on, set when the host
  // is audited; apiAuditId = the endpoint it serves, set later on the Interfaces page (empty until then).
  // Rows saved before build 5.0 have only apiAuditId; their host is the endpoint's host.
  // Discovery only: methods are recorded, never called.
  apiinterfaces: {
    label: "Interface",
    labelPlural: "Interfaces",
    verified: true,
    columns: ["id", "apiHostId", "interfaceName", "methodName", "apiAuditId", "isRegistered", "discoveredDate"],
    titles: { apiHostId: "Host", apiAuditId: "Endpoint", httpMethod: "HTTP", isRegistered: "Registered", methodName: "Method", discoveredDate: "Discovered" },
    fields: {
      id: "number", apiHostId: "ref:apihosts", apiAuditId: "ref:apiaudit",
      controllerName: "string", route: "string", httpMethod: "string",
      endpointName: "string",   // the API's name (e.g. CockyAnalytics), set from the host on import
      interfaceName: "string", implementationName: "string", serviceLifetime: "string",
      methodName: "string", isImplemented: "bool", isRegistered: "bool", discoveredDate: "date"
    },
    groups: [
      { title: "Interface", keys: ["apiHostId", "endpointName", "interfaceName", "methodName", "implementationName", "serviceLifetime", "isImplemented", "isRegistered"] },
      { title: "Associated endpoint", keys: ["apiAuditId"] },
      { title: "Endpoint mapping", keys: ["controllerName", "route", "httpMethod"] },
      { title: "Status", keys: ["id", "discoveredDate"] }
    ],
    format: {
      // Flag the mutating methods (Create*/Update*/Delete*) — a write/delete on a back-end log service is the finding
      methodName: v => {
        if (v == null || v === "") return '<span class="text-muted">—</span>';
        const s = String(v);
        const badge = /^delete/i.test(s) ? '<span class="badge text-bg-danger ms-1">delete</span>'
          : /^(create|add|insert)/i.test(s) ? '<span class="badge text-bg-warning ms-1">create</span>'
          : /^(update|put|patch|edit)/i.test(s) ? '<span class="badge text-bg-warning ms-1">update</span>'
          : "";
        return `<code>${window.Cocky.esc(s)}</code>${badge}`;
      }
    }
  },

  apiauditresults: {
    label: "Audit",
    labelPlural: "Audits",
    verified: true,
    columns: ["id", "auditDate", "auditorName", "totalApiHosts", "apiHostsInsecure", "totalApiEndpoints", "totalEndpointsInsecure", "notes"],
    fields: {
      id: "number", auditDate: "date",
      totalApiHosts: "number", apiHostsSecure: "number", apiHostsInsecure: "number",
      totalApiEndpoints: "number", totalEndpointsSecure: "number", totalEndpointsInsecure: "number",
      auditorId: "number", auditorName: "string", notes: "text"
    }
  },

  hostexceptions: {
    label: "Host exception",
    labelPlural: "Host exceptions",
    verified: true,
    columns: ["id", "apiHostId", "exceptionType", "reason", "approvedBy", "expirationDate", "active"],
    fields: {
      id: "number", apiHostId: "ref:apihosts", exceptionType: "string", reason: "text",
      approvedBy: "string", approvalDate: "date", expirationDate: "date", active: "bool",
      notes: "text", createdDate: "date"
    },
    format: { expirationDate: (v, r) => window.COCKY_SCHEMA.auditexceptions.format.expirationDate(v, r) }
  },

  // Application (Enterprise.Models.Application): an app that uses one or more host APIs.
  // Which hosts it uses lives in the ApplicationApi link table below, not on the application itself.
  apps: {
    label: "Application",
    labelPlural: "Applications",
    verified: true,
    columns: ["id", "applicationName", "applicationCode", "uiCodebase", "appOs", "hostApis", "infra", "endpointTotal", "environment", "ownerName", "isActive"],
    titles: { applicationName: "Application", applicationCode: "Code", uiCodebase: "Codebase", appOs: "App OS", hostApis: "Host APIs", infra: "Runs on", endpointTotal: "Endpoints", ownerName: "Owner", isActive: "Active" },
    fields: {
      id: "number", applicationName: "string", applicationCode: "string", description: "text",
      ownerName: "string", ownerEmail: "string", supportGroup: "string", businessUnit: "string",
      environment: "string", inventoryId: "string", isActive: "bool", createdDate: "date", modifiedDate: "date",
      // Build 4.9: where the application runs (a single web server or a web farm).
      // databaseId isn't on Enterprise.Models.Application yet; it's only shown once the API returns it.
      webServerId: "ref:webservers", webFarmId: "ref:webfarms", databaseId: "ref:databases",
      // Build 5.7: UI codebase and the vendor / OS of each tier. Keys are .NET's default JSON names for the SQL columns
      // (UI_Codebase -> uI_Codebase); the form also matches other spellings (UiCodebase, ui_codebase).
      uI_Codebase: "choice", apiVendor: "suggest", oS_API: "suggest",
      uI_HTMLVendor: "suggest", oS_UIHTML: "suggest", uI_REACTVendor: "suggest", oS_UIREACT: "suggest"
    },
    // Form labels for fields whose names don't title-case well
    labels: {
      uI_Codebase: "UI codebase", apiVendor: "API hosting vendor", oS_API: "API operating system",
      uI_HTMLVendor: "HTML UI vendor", oS_UIHTML: "HTML UI operating system",
      uI_REACTVendor: "React UI vendor", oS_UIREACT: "React UI operating system"
    },
    // Options for "choice" (dropdown) and "suggest" (free text with suggestions) fields; lists are in config.js appUi
    choices: {
      uI_Codebase: () => (window.COCKY_CONFIG?.appUi?.codebases || []).map(c => ({ value: c.value, label: c.label || c.value })),
      apiVendor: () => window.COCKY_CONFIG?.appUi?.apiVendors, uI_HTMLVendor: () => window.COCKY_CONFIG?.appUi?.vendors,
      uI_REACTVendor: () => window.COCKY_CONFIG?.appUi?.vendors,
      oS_API: () => window.COCKY_CONFIG?.appUi?.operatingSystems, oS_UIHTML: () => window.COCKY_CONFIG?.appUi?.operatingSystems,
      oS_UIREACT: () => window.COCKY_CONFIG?.appUi?.operatingSystems
    },
    groups: [
      { title: "Application", keys: ["applicationName", "applicationCode", "description", "inventoryId", "environment", "isActive"] },
      { title: "UI & platform", keys: ["uI_Codebase", "uI_HTMLVendor", "oS_UIHTML", "uI_REACTVendor", "oS_UIREACT", "apiVendor", "oS_API"] },
      { title: "Infrastructure", keys: ["webServerId", "webFarmId", "databaseId"] },
      { title: "Ownership", keys: ["ownerName", "ownerEmail", "supportGroup", "businessUnit"] },
      { title: "Status", keys: ["id", "createdDate", "modifiedDate"] }
    ]
  },

  // ApplicationApi (Enterprise.Models.ApplicationApi): one row per host API an application uses
  apphosts: {
    label: "Application API link",
    labelPlural: "Application API links",
    verified: true,
    columns: ["id", "applicationId", "apiHostId", "createdDate"],
    fields: { id: "number", applicationId: "ref:apps", apiHostId: "ref:apihosts", createdDate: "date" }
  },

  auditexceptions: {
    label: "Exception",
    labelPlural: "Exceptions",
    verified: true,
    columns: ["id", "apiAuditId", "apiRootUrl", "apiEndpointPath", "reason", "approvedBy", "expirationDate", "active"],
    fields: {
      id: "number", apiAuditId: "ref:apiaudit",
      apiRootUrl: "string", apiEndpointPath: "string",   // scope: whole API root and/or path pattern (* = wildcard)
      reason: "text", approvedBy: "string",
      approvalDate: "date", expirationDate: "date", active: "bool",
      notes: "text", createdDate: "date"
    },
    format: {
      // Show an "Expired" badge when the expiration date has passed
      expirationDate: v => {
        if (!v) return '<span class="badge text-bg-info">No expiry</span>';
        const d = Cocky.parseDate(v);
        return Cocky.fmtValue(v, "date") + (d && d < new Date() ? ' <span class="badge text-bg-danger">Expired</span>' : "");
      }
    }
  }
};

// ---- Infrastructure (build 4.9) ----
// JSON names are the ASP.NET camelCase of the SQL columns (TLSVersion -> tlsVersion, AzureURL -> azureURL,
// CName1 -> cName1). When the tables have records, the forms use the names the API actually returns.
// Computed columns: "findings" (Infra Audit result), plus the per-page ones noted below.
const INFRA_COMMON = {
  azure: ["azureURL", "azureIP", "azureSubscription", "resourceGroup", "region"],
  dns: ["cName1", "cName2", "cName3"],
  ownership: ["owner", "supportTeam", "environment", "location"]
};
Object.assign(window.COCKY_SCHEMA, {
  webservers: {
    label: "Web server", labelPlural: "Web servers", verified: true,
    columns: ["id", "serverName", "hostname", "role", "environment", "webServerType", "operatingSystem", "tlsVersion", "publicFacing", "farms", "findings", "active"],
    titles: { role: "Role", tlsVersion: "TLS", publicFacing: "Public", webServerType: "Type", operatingSystem: "OS", farms: "Farms", findings: "Findings" },
    fields: {
      id: "number", inventoryId: "string", serverName: "string", hostname: "string", ipAddress: "string",
      operatingSystem: "string", webServerType: "string", version: "string",
      azureURL: "string", azureIP: "string", cName1: "string", cName2: "string", cName3: "string",
      applicationURL: "string", environment: "string", location: "string",
      azureSubscription: "string", resourceGroup: "string", region: "string",
      owner: "string", supportTeam: "string", tlsVersion: "string",
      publicFacing: "bool", active: "bool", isProxy: "bool", isProxySlave: "bool", notes: "text", createdDate: "date"
    },
    groups: [
      { title: "Server", keys: ["serverName", "hostname", "ipAddress", "inventoryId", "operatingSystem", "webServerType", "version", "tlsVersion", "applicationURL", "publicFacing", "active"] },
      { title: "Proxy role", keys: ["isProxy", "isProxySlave"] },
      { title: "Ownership", keys: INFRA_COMMON.ownership },
      { title: "DNS names", keys: INFRA_COMMON.dns },
      { title: "Azure", keys: INFRA_COMMON.azure },
      { title: "Notes & status", keys: ["notes", "id", "createdDate"] }
    ]
  },

  webfarms: {
    label: "Web farm", labelPlural: "Web farms", verified: true,
    columns: ["id", "farmName", "environment", "loadBalancerName", "url", "tlsVersion", "publicFacing", "members", "findings", "enabled"],
    titles: { farmName: "Farm", loadBalancerName: "Load balancer", url: "URL", tlsVersion: "TLS", publicFacing: "Public", members: "Member servers", findings: "Findings" },
    fields: {
      id: "number", inventoryId: "string", farmName: "string", description: "text",
      loadBalancerName: "string", loadBalancerType: "string", virtualIpAddress: "string", url: "string",
      azureURL: "string", azureIP: "string", cName1: "string", cName2: "string", cName3: "string",
      applicationURL: "string", environment: "string", location: "string",
      azureSubscription: "string", resourceGroup: "string", region: "string",
      owner: "string", supportTeam: "string", tlsVersion: "string", backendPoolCount: "number",
      healthProbeUrl: "string", publicFacing: "bool", enabled: "bool", notes: "text", createdDate: "date"
    },
    groups: [
      { title: "Farm", keys: ["farmName", "description", "inventoryId", "url", "applicationURL", "tlsVersion", "publicFacing", "enabled"] },
      { title: "Load balancer", keys: ["loadBalancerName", "loadBalancerType", "virtualIpAddress", "backendPoolCount", "healthProbeUrl"] },
      { title: "Ownership", keys: INFRA_COMMON.ownership },
      { title: "DNS names", keys: INFRA_COMMON.dns },
      { title: "Azure", keys: INFRA_COMMON.azure },
      { title: "Notes & status", keys: ["notes", "id", "createdDate"] }
    ]
  },

  // Link table: which web servers are in which farm (no PUT: add or remove only)
  webfarmservers: {
    label: "Farm member", labelPlural: "Farm members", verified: true,
    columns: ["id", "webFarmId", "webServerId"],
    fields: { id: "number", webFarmId: "ref:webfarms", webServerId: "ref:webservers" }
  },

  databaseservers: {
    label: "Database server", labelPlural: "Database servers", verified: true,
    columns: ["id", "serverName", "hostname", "environment", "databasePlatform", "version", "backupSolution", "publicFacing", "databaseCount", "findings", "active"],
    titles: { databasePlatform: "Platform", backupSolution: "Backup", publicFacing: "Public", databaseCount: "Databases", findings: "Findings" },
    fields: {
      id: "number", inventoryId: "string", serverName: "string", hostname: "string", ipAddress: "string",
      databasePlatform: "string", version: "string", databaseInstance: "string",
      azureURL: "string", azureIP: "string", cName1: "string", cName2: "string", cName3: "string",
      environment: "string", location: "string",
      azureSubscription: "string", resourceGroup: "string", region: "string",
      owner: "string", supportTeam: "string", backupSolution: "string", recoveryModel: "string",
      publicFacing: "bool", active: "bool", notes: "text", createdDate: "date"
    },
    groups: [
      { title: "Server", keys: ["serverName", "hostname", "ipAddress", "inventoryId", "databasePlatform", "version", "databaseInstance", "publicFacing", "active"] },
      { title: "Backup", keys: ["backupSolution", "recoveryModel"] },
      { title: "Ownership", keys: INFRA_COMMON.ownership },
      { title: "DNS names", keys: INFRA_COMMON.dns },
      { title: "Azure", keys: INFRA_COMMON.azure },
      { title: "Notes & status", keys: ["notes", "id", "createdDate"] }
    ]
  },

  databases: {
    label: "Database", labelPlural: "Databases", verified: true,
    columns: ["id", "databaseName", "databaseServerId", "databaseType", "classification", "dataFlags", "encryptionEnabled", "backupRequired", "usedBy", "findings", "active"],
    titles: { databaseName: "Database", databaseServerId: "Server", databaseType: "Type", dataFlags: "Holds", encryptionEnabled: "Encrypted", backupRequired: "Backup req.", usedBy: "Used by", findings: "Findings" },
    fields: {
      id: "number", inventoryId: "string", databaseServerId: "ref:databaseservers", databaseName: "string",
      description: "text", databaseType: "string", version: "string", classification: "string",
      owner: "string", supportTeam: "string",
      backupRequired: "bool", encryptionEnabled: "bool", containsPII: "bool", containsPHI: "bool", containsPCI: "bool",
      active: "bool", notes: "text", createdDate: "date"
    },
    // New records start with the table's defaults (BackupRequired = 1)
    defaults: { backupRequired: true },
    groups: [
      { title: "Database", keys: ["databaseName", "databaseServerId", "description", "inventoryId", "databaseType", "version", "active"] },
      { title: "Data protection", keys: ["classification", "containsPII", "containsPHI", "containsPCI", "encryptionEnabled", "backupRequired"] },
      { title: "Ownership", keys: ["owner", "supportTeam"] },
      { title: "Notes & status", keys: ["notes", "id", "createdDate"] }
    ]
  },

  // Services (build 6.3). A service belongs to one API host (apiHostId) and is attached to that host's endpoints
  // through the apiserviceendpoints join table. Managed on the Services page; wired to endpoints on the Service Map.
  apiservices: {
    label: "Service", labelPlural: "Services", verified: true,
    columns: ["id", "serviceName", "apiHostId", "serviceType", "interfaceName", "serviceOwner", "isActive"],
    titles: { apiHostId: "Host", serviceType: "Type", interfaceName: "Interface", serviceOwner: "Owner", isActive: "Active" },
    fields: {
      id: "number", serviceName: "string", apiHostId: "ref:apihosts", apiHostName: "string",
      interfaceId: "number", interfaceName: "string", implementationClass: "string",
      description: "text", serviceType: "string", serviceOwner: "string",
      isActive: "bool", createdDate: "date", modifiedDate: "date"
    },
    defaults: { isActive: true },
    groups: [
      { title: "Service", keys: ["serviceName", "apiHostId", "apiHostName", "serviceType", "serviceOwner", "isActive", "description"] },
      { title: "Interface / implementation", keys: ["interfaceName", "interfaceId", "implementationClass"] },
      { title: "Status", keys: ["id", "createdDate", "modifiedDate"] }
    ]
  },

  // Service <-> endpoint links (build 6.3). One row per (serviceId, apiAuditId). apiHostId is copied from the service.
  // Written by the Service Map page; not edited through the generic add/edit form.
  apiserviceendpoints: {
    label: "Service link", labelPlural: "Service links", verified: true,
    columns: ["id", "serviceId", "apiAuditId", "apiHostId", "createdDate"],
    fields: {
      id: "number", serviceId: "ref:apiservices", apiAuditId: "ref:apiaudit",
      apiHostId: "ref:apihosts", createdDate: "date"
    }
  },

  // Discovered EF tables (build 6.5). Read-only inventory written by the host-side table discovery. Shown on the
  // Database Tables page; not edited through the generic form.
  databasetables: {
    label: "Database table", labelPlural: "Database tables", verified: true,
    columns: ["tableName", "schemaName", "modelName", "columnCount", "lastAuditDate", "isActive"],
    titles: { tableName: "Table", schemaName: "Schema", modelName: "Model", columnCount: "Columns", lastAuditDate: "Last audit", isActive: "Active" },
    fields: {
      id: "number", tableName: "string", schemaName: "string", modelName: "string", columnCount: "number",
      createdDate: "date", lastAuditDate: "date", isActive: "bool"
    }
  },

  // Enterprise(9) per-host log setup (build 6.4). One row per log a host exposes. endpointUrl is the exact route
  // (a path joined to the host's URL, or a full absolute URL when a region's base differs).
  enterprise9: {
    label: "Enterprise(9) log", labelPlural: "Enterprise(9) logs", verified: true,
    columns: ["id", "apiHostId", "logName", "endpointUrl", "httpMethod", "isRequired", "isImplemented", "isActive", "lastValidated"],
    titles: { apiHostId: "Host", logName: "Log", endpointUrl: "Route", httpMethod: "Method", isRequired: "Required", isImplemented: "Implemented", lastValidated: "Last validated" },
    fields: {
      id: "number", apiHostId: "ref:apihosts", apiHostName: "string",
      logName: "string", logDescription: "string", endpointUrl: "string", httpMethod: "choice",
      isRequired: "bool", isImplemented: "bool", lastValidated: "date", notes: "text",
      isActive: "bool", createdDate: "date", modifiedDate: "date"
    },
    choices: { httpMethod: ["GET", "POST", "PUT", "PATCH", "DELETE"] },
    defaults: { isActive: true, httpMethod: "GET" },
    groups: [
      { title: "Log", keys: ["logName", "apiHostId", "apiHostName", "logDescription", "endpointUrl", "httpMethod", "isActive"] },
      { title: "Compliance", keys: ["isRequired", "isImplemented", "lastValidated", "notes"] },
      { title: "Status", keys: ["id", "createdDate", "modifiedDate"] }
    ]
  }
});

// ---- Form sections ----
// The add/edit dialog groups fields under these headings. A section starts expanded when it's
// first, or when the record already has something filled in there.
const DETAIL_GROUPS = [
  { detail: true, title: "Ownership (department / building)", keys: ["businessUnitName", "businessUnitOwnerId", "groupId", "groupDescription", "buildingId", "buildingName"] },
  { detail: true, title: "Ops contacts", keys: ["techContactName", "techContactEmail", "techContactPhone", "techContactFax", "securityEmail", "securityPhone"] },
  { detail: true, title: "Auditor", keys: ["auditorId", "auditorName", "auditorEmail", "auditorEmployeeId", "auditorDepartment"] },
  { detail: true, title: "Platform & data", keys: ["environment", "applicationName", "osType", "frameworkVersion", "databaseFramework", "databaseType", "databaseConnectionString", "dbaId", "dbaName", "hashType", "sourceRepository", "securityClassification"] },
  { detail: true, title: "Azure", keys: ["azureSubscriptionId", "azureResourceGroup"] },
  { detail: true, title: "Network", keys: ["hostName", "fqdn", "iPv4Address", "iPv6Address", "primaryPort", "secondaryPort", "secondaryV4", "secondaryV6", "httpPortV4", "httpPortV6", "sslSupported", "httpSupported", "hasProxy", "proxyType", "proxyEntranceV4", "proxyEntranceV6", "corsPath", "allowedRanges", "deniedRanges"] },
  { detail: true, title: "Services", keys: ["servicesAttached", "servicesJson"] }
];
window.COCKY_SCHEMA.apihosts.defaultView = "core";   // Edit shows core fields; the Details button shows the rest
window.COCKY_SCHEMA.apihosts.groups = [
  { title: "API & Swagger", keys: ["apiHostName", "apiHostUrl", "swaggerUsername", "swaggerPassword", "family", "isSecure", "active", "isActive"] },
  ...DETAIL_GROUPS,
  { title: "Audit status", keys: ["id", "lastAuditDate", "lastAuditId", "createdDate"] }
];
window.COCKY_SCHEMA.apiaudit.groups = [
  { title: "Endpoint", keys: ["description", "type", "endpointType", "url", "apiRoot", "apiHostId", "family", "hasAuthEnabled", "authType", "endpointSecure", "isActive", "swaggerOperationId", "swaggerVersion", "notes"] },
  ...DETAIL_GROUPS,
  { title: "Audit status", keys: ["id", "lastAuditDate", "auditResultId", "lastResponseMs", "lastStatusCode", "createdDate", "modifiedDate"] }
];

// ---- Run Audit -> /api/ApiAuditResults ----
// One audit result = one summary record for the whole run.
// pairs = [{ endpoint, check }], hosts = all Apihost records.

// Counts for the run. An endpoint is "secure" if it was tested over HTTPS.
// A host is "secure" if its apiHostUrl is HTTPS (falls back to its isSecure flag).
window.summarizeAudit = function (pairs, hosts) {
  const hostIds = [...new Set(pairs.map(p => p.endpoint.apiHostId).filter(id => id != null))];
  const auditedHosts = hostIds.map(id => hosts.find(h => h.id === id)).filter(Boolean);
  const hostSecure = h => /^https:/i.test(h.apiHostUrl || "") || (!h.apiHostUrl && !!h.isSecure);
  const epSecure = pairs.filter(p => p.check.secure).length;
  const hSecure = auditedHosts.filter(hostSecure).length;
  return {
    totalApiHosts: auditedHosts.length,
    apiHostsSecure: hSecure,
    apiHostsInsecure: auditedHosts.length - hSecure,
    totalApiEndpoints: pairs.length,
    totalEndpointsSecure: epSecure,
    totalEndpointsInsecure: pairs.length - epSecure
  };
};

window.buildAuditResultPayload = function (pairs, hosts, { auditorId, auditorName, notes }) {
  const lines = pairs.map(({ endpoint: e, check: c }) => {
    const head = `#${e.id} ${e.description || ""} - ${c.verdict.toUpperCase()}` +
      `${c.status ? ` (HTTP ${c.status}` : " ("}${c.ms != null ? `${c.status ? ", " : ""}${Math.round(c.ms)} ms` : ""}) ${c.url || "(no url)"}`;
    const issues = c.findings.filter(f => f.level === "warn" || f.level === "fail")
      .map(f => `   [${f.level.toUpperCase()}] ${f.text}`);
    return [head.replace(" ()", ""), ...issues].join("\n");
  });
  let text = [notes, lines.join("\n")].filter(Boolean).join("\n\n");
  if (text.length > 4000) text = text.slice(0, 3990) + "\n…";
  return {
    auditDate: new Date().toISOString(),
    ...window.summarizeAudit(pairs, hosts),
    auditorId: auditorId || 0,
    auditorName: auditorName || null,
    notes: text
  };
};

// ---- Users & Access (build 5.3) ----
// Users: Enterprise.Models.User (/api/Users). Add/Edit only touch the registration fields (first/last name, user name, email,
// password on add); password and reset-token fields are never shown or sent. The API's PUT leaves any field that isn't sent
// unchanged. ApplicationIds / ApplicationPermissions are edited in the Access dialog.
Object.assign(window.COCKY_SCHEMA, {
  // Only the registration fields are managed here; users update the rest of their profile themselves after signing in.
  users: {
    label: "User", labelPlural: "Users", verified: true,
    columns: ["id", "username", "fullname", "email", "roles", "groups", "appAccess", "apiAccess", "siteAccess", "findings"],
    titles: { username: "User name", fullname: "Name", roles: "Roles", groups: "Groups", appAccess: "Apps", apiAccess: "APIs", siteAccess: "Sites", findings: "Findings" },
    fields: { id: "number", firstname: "string", lastname: "string", fullname: "string", username: "string", email: "string",
      role: "string", role2: "string", role3: "string" }
  },

  sites: {
    label: "Site", labelPlural: "Sites", verified: true,
    columns: ["id", "siteName", "siteCode", "city", "state", "country", "siteManager", "siteUsers", "isActive"],
    titles: { siteName: "Site", siteCode: "Code", siteManager: "Manager", siteUsers: "Users", isActive: "Active" },
    fields: {
      id: "number", siteName: "string", siteCode: "string", address1: "string", address2: "string",
      city: "string", state: "string", postalCode: "string", country: "string", phoneNumber: "string",
      siteManager: "string", isActive: "bool", notes: "text"
    },
    defaults: { isActive: true },
    groups: [
      { title: "Site", keys: ["siteName", "siteCode", "siteManager", "phoneNumber", "isActive"] },
      { title: "Address", keys: ["address1", "address2", "city", "state", "postalCode", "country"] },
      { title: "Notes", keys: ["notes", "id"] }
    ]
  },

  // ApiAccessPermissions: a user's access to a host API (ApiId = Apihosts.Id)
  apiaccess: {
    label: "API permission", labelPlural: "API permissions", verified: true,
    columns: ["id", "userId", "apiId", "permissionLevel", "isEnabled", "grantedBy", "createdDate"],
    fields: { id: "number", userId: "number", apiId: "ref:apihosts", permissionLevel: "string", isEnabled: "bool", createdDate: "date", grantedBy: "string" }
  },

  // SiteAccessPermissions: a user's access to a site
  siteaccess: {
    label: "Site permission", labelPlural: "Site permissions", verified: true,
    columns: ["id", "userId", "siteId", "accessLevel", "isEnabled", "grantedBy", "grantedDate", "expirationDate", "reviewedDate"],
    fields: { id: "number", userId: "number", siteId: "ref:sites", accessLevel: "string", isEnabled: "bool",
      grantedDate: "date", grantedBy: "string", expirationDate: "date", reviewedDate: "date", reviewedBy: "string" }
  }
});

// WorkerTroubleTickets (build 5.8): one ticket per failing endpoint (ApiName + Endpoint); a repeat raises IncidentCount.
// ReportedOn is set by the API on create; TicketNumber isn't changed by its PUT.
Object.assign(window.COCKY_SCHEMA, {
  troubletickets: {
    label: "Trouble ticket", labelPlural: "Trouble tickets", verified: true,
    columns: ["ticketNumber", "severity", "status", "apiName", "endpoint", "environment", "owner", "incidentCount", "isHardDown", "assignedTo", "reportedOn", "resolvedOn"],
    titles: { ticketNumber: "Ticket", apiName: "API", owner: "Owner", incidentCount: "Incidents", isHardDown: "Hard down", assignedTo: "Assigned to", reportedOn: "Reported", resolvedOn: "Resolved" },
    fields: {
      id: "number", ticketNumber: "string", apiName: "string", endpoint: "string", environment: "string",
      severity: "choice", status: "choice", reportedBy: "string", reportedOn: "date", resolvedOn: "date",
      description: "text", resolutionNotes: "text", assignedTo: "string", isHardDown: "bool", incidentCount: "number",
      // Build 5.8 additions (all nullable)
      impactedUsers: "number", businessUnit: "string", rootCause: "text", evidenceUrl: "string", auditorNotes: "text", applicationOwner: "string"
    },
    labels: { apiName: "API name", isHardDown: "Hard down", incidentCount: "Incident count", impactedUsers: "Impacted users",
      businessUnit: "Business unit", rootCause: "Root cause", evidenceUrl: "Evidence URL", auditorNotes: "Auditor notes", applicationOwner: "Application owner" },
    choices: {
      severity: () => window.COCKY_CONFIG?.tickets?.severities || ["Critical", "High", "Medium", "Low"],
      status: () => window.COCKY_CONFIG?.tickets?.statuses || ["Open", "In Progress", "Resolved", "Closed"]
    },
    defaults: { status: "Open", severity: "Critical", isHardDown: true, incidentCount: 1 },
    groups: [
      { title: "Ticket", keys: ["ticketNumber", "apiName", "endpoint", "environment", "severity", "status", "isHardDown", "incidentCount", "description"] },
      { title: "Impact & ownership", keys: ["impactedUsers", "businessUnit", "applicationOwner"] },
      { title: "Evidence & notes", keys: ["evidenceUrl", "auditorNotes"] },
      { title: "Assignment & resolution", keys: ["assignedTo", "reportedBy", "reportedOn", "resolvedOn", "rootCause", "resolutionNotes"] },
      { title: "Record", keys: ["id"] }
    ]
  }
});

// Usergroups (build 5.8, Enterprise.Models.Usergroup). Users join a group through their groupid1..5 slots, which hold Groupid.
Object.assign(window.COCKY_SCHEMA, {
  usergroups: {
    label: "Group", labelPlural: "Groups", verified: true,
    columns: ["id", "groupdescription", "groupid", "owner", "groupcompanyid", "members", "findings"],
    titles: { groupdescription: "Group", groupid: "Group code", owner: "Owner", groupcompanyid: "Company", members: "Members", findings: "Findings" },
    fields: { id: "number", groupid: "string", groupdescription: "string", groupownerid: "ref:users", groupcompanyid: "string" },
    labels: { groupid: "Group code (Groupid)", groupdescription: "Description", groupownerid: "Group owner", groupcompanyid: "Company ID" },
    groups: [{ title: "Group", keys: ["groupdescription", "groupid", "groupownerid", "groupcompanyid", "id"] }]
  }
});

// Customer (build 5.8, Enterprise.Models.Customer). UserId is required; CreatedAt isn't nullable. Portfolios is a navigation
// collection: the form leaves it alone (sent as an empty list).
Object.assign(window.COCKY_SCHEMA, {
  customers: {
    label: "Customer", labelPlural: "Customers", verified: true,
    columns: ["id", "fullName", "userId", "tenantid", "portfolios", "tickets", "createdAt"],
    titles: { fullName: "Customer", userId: "User ID", tenantid: "Tenant", portfolios: "Portfolios", tickets: "Customer tickets", createdAt: "Created" },
    fields: { id: "number", tenantid: "string", userId: "string", fullName: "string", createdAt: "date" },
    labels: { tenantid: "Tenant ID", userId: "User ID (required)", fullName: "Full name", createdAt: "Created at" },
    groups: [{ title: "Customer", keys: ["fullName", "userId", "tenantid", "createdAt", "id"] }]
  }
});

// SQL catalog (build 5.9): AuditSqlServers -> AuditSqlTables (SqlServerId) -> AuditSqlFields (SqlTableId)
Object.assign(window.COCKY_SCHEMA, {
  sqlservers: {
    label: "SQL server", labelPlural: "SQL servers", verified: true,
    columns: ["id", "serverName", "databaseName", "databaseType", "databaseVersion", "environment", "protection", "contacts", "tableCount", "sensitive", "findings", "active"],
    titles: { serverName: "Server", databaseName: "Database", databaseType: "Type", databaseVersion: "Version", protection: "Protection", contacts: "Owner / DBA", tableCount: "Tables", sensitive: "PHI / PII", findings: "Findings", active: "Active" },
    fields: {
      id: "number", serverName: "string", databaseName: "string", databaseType: "choice", databaseVersion: "string", environment: "string",
      ownerName: "string", ownerEmail: "string", ownerPhone: "string", dbaName: "string", dbaEmail: "string", dbaPhone: "string",
      dbContextName: "string", connectionStringName: "string", description: "text", createdDate: "date", active: "bool",
      databaseSizeMB: "number", backupPolicy: "string", geoReplicationEnabled: "bool", tdeEnabled: "bool", defenderEnabled: "bool"
    },
    labels: { dbaName: "DBA name", dbaEmail: "DBA email", dbaPhone: "DBA phone", dbContextName: "DbContext name", connectionStringName: "Connection string name",
      databaseSizeMB: "Database size (MB)", backupPolicy: "Backup policy", geoReplicationEnabled: "Geo-replication enabled", tdeEnabled: "TDE enabled", defenderEnabled: "Defender for SQL enabled" },
    choices: { databaseType: () => window.COCKY_CONFIG?.sqlCatalog?.databaseTypes || ["MSSQL", "Oracle", "MySQL", "PostgreSQL"] },
    defaults: { active: true, databaseType: "MSSQL", geoReplicationEnabled: false, tdeEnabled: false, defenderEnabled: false },
    groups: [
      { title: "Database", keys: ["serverName", "databaseName", "databaseType", "databaseVersion", "environment", "databaseSizeMB", "active"] },
      { title: "Protection", keys: ["tdeEnabled", "defenderEnabled", "geoReplicationEnabled", "backupPolicy"] },
      { title: "Owner", keys: ["ownerName", "ownerEmail", "ownerPhone"] },
      { title: "DBA", keys: ["dbaName", "dbaEmail", "dbaPhone"] },
      { title: "Application", keys: ["dbContextName", "connectionStringName", "description"] },
      { title: "Record", keys: ["id", "createdDate"] }
    ]
  },
  sqltables: {
    label: "Table", labelPlural: "Tables", verified: true,
    columns: ["id", "table", "description", "fieldCount", "flags", "controls", "someRowCount", "findings"],
    titles: { table: "Table", fieldCount: "Columns", flags: "PHI / PII", controls: "Controls", someRowCount: "Rows / size", findings: "Findings" },
    fields: { id: "number", sqlServerId: "ref:sqlservers", schemaName: "string", tableName: "string", description: "text",
      containsPHI: "bool", containsPII: "bool", someRowCount: "number", tableSizeMB: "number", lastStatisticsUpdate: "date",
      hasRowLevelSecurity: "bool", hasDynamicDataMasking: "bool", classificationStatus: "suggest" },
    labels: { sqlServerId: "SQL server", containsPHI: "Contains PHI", containsPII: "Contains PII", someRowCount: "Row count", tableSizeMB: "Table size (MB)",
      lastStatisticsUpdate: "Statistics last updated", hasRowLevelSecurity: "Row-level security", hasDynamicDataMasking: "Dynamic data masking", classificationStatus: "Classification status" },
    choices: { classificationStatus: () => ["Not reviewed", "In review", "Classified", "Approved"] },
    defaults: { schemaName: "dbo", containsPHI: false, containsPII: false, hasRowLevelSecurity: false, hasDynamicDataMasking: false },
    groups: [
      { title: "Table", keys: ["sqlServerId", "schemaName", "tableName", "description", "containsPHI", "containsPII", "classificationStatus"] },
      { title: "Controls & size", keys: ["hasRowLevelSecurity", "hasDynamicDataMasking", "someRowCount", "tableSizeMB", "lastStatisticsUpdate", "id"] }
    ]
  },
  sqlfields: {
    label: "Column", labelPlural: "Columns", verified: true,
    columns: ["id", "columnName", "type", "keys", "isNullable", "sensitivity", "isEncrypted", "description", "findings"],
    titles: { columnName: "Column", type: "Type", keys: "Key", isNullable: "Nullable", sensitivity: "PHI / PII", isEncrypted: "Encrypted / masked / label", findings: "Findings" },
    fields: { id: "number", sqlTableId: "ref:sqltables", columnName: "string", dataType: "string", maxLength: "number",
      isPrimaryKey: "bool", isForeignKey: "bool", isNullable: "bool", containsPII: "bool", containsPHI: "bool", isEncrypted: "bool", description: "text",
      sensitivityLabel: "suggest", maskingRule: "string" },
    labels: { sqlTableId: "Table", containsPII: "Contains PII", containsPHI: "Contains PHI", isEncrypted: "Encrypted", sensitivityLabel: "Sensitivity label", maskingRule: "Masking rule (e.g. partial(0,\"XXX-XX-\",4))" },
    choices: { sensitivityLabel: () => ["Public", "General", "Confidential", "Confidential - GDPR", "Highly Confidential", "Highly Confidential - GDPR"] },
    defaults: { isPrimaryKey: false, isForeignKey: false, isNullable: true, containsPII: false, containsPHI: false, isEncrypted: false },
    groups: [
      { title: "Column", keys: ["sqlTableId", "columnName", "dataType", "maxLength", "isPrimaryKey", "isForeignKey", "isNullable", "description", "id"] },
      { title: "Sensitivity & protection", keys: ["containsPHI", "containsPII", "sensitivityLabel", "isEncrypted", "maskingRule"] }
    ]
  }
});
