// Field definitions used by the add/edit forms and tables.
//
// When a resource already has records, the form uses the fields found on the
// real records and these lists only supply types/labels. When there are no
// records yet, these lists decide what the "Add" form shows.
//
// Types: string | text | number | bool | date | guid | password | ref:<resource> (dropdown of that resource)
//
// All four match the real API. Ids are generated by SQL Server and are never
// sent when creating a record.

window.COCKY_SCHEMA = {
  apiaudit: {
    label: "Endpoint",
    labelPlural: "Endpoints",
    verified: true,
    columns: ["id", "description", "apiHostId", "url", "environment", "endpointType", "isActive", "lastAuditDate"],
    fields: {
      id: "number", auditorId: "number", description: "string", family: "string",
      url: "string", apiRoot: "string", type: "string",
      servicesAttached: "bool", servicesJson: "text",
      iPv4Address: "string", iPv6Address: "string", hostName: "string",
      hasProxy: "bool", proxyEntranceV4: "string", proxyEntranceV6: "string", proxyType: "string",
      databaseFramework: "string", databaseConnectionString: "string", databaseType: "string",
      hasAuthEnabled: "bool", authType: "string",
      auditorName: "string", auditorEmail: "string", auditorEmployeeId: "string", auditorDepartment: "string",
      businessUnitName: "string", businessUnitOwnerId: "number",
      primaryPort: "number", secondaryPort: "number", secondaryV4: "string", secondaryV6: "string",
      fqdn: "string", osType: "string", frameworkVersion: "string",
      groupId: "number", groupDescription: "string", buildingId: "number", buildingName: "string",
      techContactName: "string", techContactEmail: "string", techContactFax: "string", techContactPhone: "string",
      securityEmail: "string", securityPhone: "string", dbaId: "number", dbaName: "string",
      hashType: "string", endpointType: "string", sslSupported: "bool", httpSupported: "bool",
      httpPortV4: "number", httpPortV6: "number", corsPath: "string",
      allowedRanges: "string", deniedRanges: "string",
      createdDate: "date", modifiedDate: "date", lastAuditDate: "date", isActive: "bool",
      environment: "string", applicationName: "string", sourceRepository: "string",
      azureSubscriptionId: "guid", azureResourceGroup: "string",
      apiHostId: "ref:apihosts", auditResultId: "number", endpointSecure: "bool",
      swaggerOperationId: "string", swaggerVersion: "string", notes: "text", securityClassification: "string"
    }
  },

  apihosts: {
    label: "Host",
    labelPlural: "Hosts",
    verified: true,
    columns: ["id", "apiHostName", "apiHostUrl", "isSecure", "active", "lastAuditDate", "createdDate"],
    fields: {
      id: "number", apiHostName: "string", apiHostUrl: "string",
      swaggerUsername: "string", swaggerPassword: "password",
      isSecure: "bool", lastAuditDate: "date", lastAuditId: "number",
      active: "bool", createdDate: "date"
    }
  },

  apiauditresults: {
    label: "Audit",
    labelPlural: "Audits",
    verified: true,
    columns: ["id", "auditDate", "auditorName", "totalApiHosts", "apiHostsInsecure", "totalApiEndpoints", "totalEndpointsInsecure", "notes"],
    fields: {
      id: "number", auditDate: "date",
      totalApiHosts: "number", apiHostsSecure: "number", apiHostsInsecure: "number",
      totalApiEndpoints: "number", totalEndpointsSecure: "number", totalEndpointsInsecure: "number",
      auditorId: "number", auditorName: "string", notes: "text"
    }
  },

  auditexceptions: {
    label: "Exception",
    labelPlural: "Exceptions",
    verified: true,
    columns: ["id", "apiAuditId", "apiRootUrl", "apiEndpointPath", "reason", "approvedBy", "expirationDate", "active"],
    fields: {
      id: "number", apiAuditId: "ref:apiaudit",
      apiRootUrl: "string", apiEndpointPath: "string",   // scope: whole API root and/or path pattern (* = wildcard)
      reason: "text", approvedBy: "string",
      approvalDate: "date", expirationDate: "date", active: "bool",
      notes: "text", createdDate: "date"
    },
    format: {
      // Show an "Expired" badge when the expiration date has passed
      expirationDate: v => {
        if (!v) return '<span class="badge text-bg-info">No expiry</span>';
        const d = Cocky.parseDate(v);
        return Cocky.fmtValue(v, "date") + (d && d < new Date() ? ' <span class="badge text-bg-danger">Expired</span>' : "");
      }
    }
  }
};

// ---- Run Audit -> /api/ApiAuditResults ----
// One audit result = one summary record for the whole run.
// pairs = [{ endpoint, check }], hosts = all Apihost records.

// Counts for the run. An endpoint is "secure" if it was tested over HTTPS.
// A host is "secure" if its apiHostUrl is HTTPS (falls back to its isSecure flag).
window.summarizeAudit = function (pairs, hosts) {
  const hostIds = [...new Set(pairs.map(p => p.endpoint.apiHostId).filter(id => id != null))];
  const auditedHosts = hostIds.map(id => hosts.find(h => h.id === id)).filter(Boolean);
  const hostSecure = h => /^https:/i.test(h.apiHostUrl || "") || (!h.apiHostUrl && !!h.isSecure);
  const epSecure = pairs.filter(p => p.check.secure).length;
  const hSecure = auditedHosts.filter(hostSecure).length;
  return {
    totalApiHosts: auditedHosts.length,
    apiHostsSecure: hSecure,
    apiHostsInsecure: auditedHosts.length - hSecure,
    totalApiEndpoints: pairs.length,
    totalEndpointsSecure: epSecure,
    totalEndpointsInsecure: pairs.length - epSecure
  };
};

window.buildAuditResultPayload = function (pairs, hosts, { auditorId, auditorName, notes }) {
  const lines = pairs.map(({ endpoint: e, check: c }) => {
    const head = `#${e.id} ${e.description || ""} - ${c.verdict.toUpperCase()}` +
      `${c.status ? ` (HTTP ${c.status}` : " ("}${c.ms != null ? `${c.status ? ", " : ""}${Math.round(c.ms)} ms` : ""}) ${c.url || "(no url)"}`;
    const issues = c.findings.filter(f => f.level === "warn" || f.level === "fail")
      .map(f => `   [${f.level.toUpperCase()}] ${f.text}`);
    return [head.replace(" ()", ""), ...issues].join("\n");
  });
  let text = [notes, lines.join("\n")].filter(Boolean).join("\n\n");
  if (text.length > 4000) text = text.slice(0, 3990) + "\n…";
  return {
    auditDate: new Date().toISOString(),
    ...window.summarizeAudit(pairs, hosts),
    auditorId: auditorId || 0,
    auditorName: auditorName || null,
    notes: text
  };
};
