SQL
CREATE TABLE CipherSupport
(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
CipherName TEXT NOT NULL,
Version TEXT NOT NULL,
Description TEXT NOT NULL,
CipherKey TEXT,
IsActive INTEGER NOT NULL DEFAULT 1,
DateCreated TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
16
);
